management:
  endpoints:
    web:
      base-path: /mon
      exposure:
        include: "*"

server:
  port: 8080


spring:
  freemarker:
    charset: utf-8

myapp:
  officialCats:
    - Борис
    - Дуся
    - Семён